version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --forward-to http://host.docker.internal:3000/api/stripe-webhook"
    env_file:
      - .env
