import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../component/nav/navBar";
import Footer from "@/component/footer/footer";
import "material-icons/iconfont/material-icons.css";
import CartProvider from "@/providers/CartProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2 Hand's Product",
  description: "Generated by 2 Hand's Product",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster toastOptions={{
          style:{
            background: 'rgb(51 65 85)',
            color: '#fff',
          }
        }}
        />
        <CartProvider>
          <div className="sticky top-0 z-50">
            <NavBar />
          </div>
          <main className="h-full bg-base-200 min-h-screen pt-5">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
