import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '../component/nav/navBar'
import 'material-icons/iconfont/material-icons.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "2 Hand's Product",
  description: "Generated by 2 Hand's Product",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={inter.className}>
        <NavBar />
        <main className="my-8">
          {children}
        </main>
      </body>
    </html>
  )
}
