import UserNav from "@/component/usernav/usernav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "2 Hand's Product",
  description: "Generated by 2 Hand's Product",
};

export default async function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <div className="flex flex-row min-h-full max-w-screen-xl mx-auto">
        <UserNav />
        {children}
    </div>
            
  );
}
